
#READ PASSWORD
#-------------
$UserFile = "c:\cloud-init\username.store"
$File = "c:\cloud-init\password.store"
$KeyFile ="c:\cloud-init\key.store"

$filecheck = $UserFile, $File, $KeyFile
$result = ($filecheck | Test-Path) -notcontains $false


if($result){
    echo "Found all Username and Password Files"

    $key = Get-Content $KeyFile
    $SECURESTRING_PASSWORD = Get-Content $File | ConvertTo-SecureString -Key $key
    $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SECURESTRING_PASSWORD)
    $PASSWORD = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
    $USERNAME = Get-Content $UserFile
    
    $USER_NAME = $USERNAME
    $ADMIN_PASS = $PASSWORD

    $LOCALUSER = "$HOSTNAME\$USER_NAME"
    $ADMIN_PASSWORD = ConvertTo-SecureString -String $ADMIN_PASS -AsPlainText -Force

    
    if ($USER_NAME) {
        Write-Host "Username: $($LOCALUSER)" -F Green
        if($USER_NAME -eq "Administrator"){
            if ($ADMIN_PASS) {
                Write-Host "Setting Admin Password" -F Blue
                Set-LocalUser -Name Administrator -Password $ADMIN_PASSWORD -Confirm:$false
            }else{
                Write-Host "No Admin Password specified" -F Yellow
            }
        }else{
            Write-Host "Switching Admin to User: $($USER_NAME)" -F Blue
            New-LocalUser -Name "$USER_NAME" -Password $ADMIN_PASSWORD -FullName "$USER_NAME" -Description "New Admin user Generated By proxmox-cloud-init"
            Add-LocalGroupMember -Group Administrators -Member $USER_NAME
            Disable-LocalUser -Name "Administrator"
            Write-Host ""
            Write-Host "IMPORTANT!  Administrator disabled new LocalAdmin=$($USER_NAME)"
        }
        #---------- ALL FILES READ AND COMPLETE --------------------------
        # Auto-login
        $RegPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
        $RegROPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce"
        Set-ItemProperty $RegPath "AutoAdminLogon" -Value "1" -type String  
        Set-ItemProperty $RegPath "DefaultUsername" -Value "$HOSTNAME\$USER_NAME" -type String
        Set-ItemProperty $RegPath "DefaultPassword" -Value "$ADMIN_PASS" -type String
        Set-ItemProperty $RegPath "AutoLogonCount" -Value "1" -type DWord
        Set-ItemProperty $RegROPath "(Default)" -Value 'c:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe -noexit "c:\cloud-init\cloud-init.user.ps1"' -type String
    }
    rm -Force $File -ErrorAction Ignore 
}