
#READ PASSWORD
#-------------
$UserFile = "c:\cloud-init\username.store"
$File = "c:\cloud-init\password.store"
$KeyFile ="c:\cloud-init\key.store"
$key = Get-Content $KeyFile
$PASSWORD = Get-Content $File | ConvertTo-SecureString -Key $key
$USERNAME = Get-Content $UserFile
$USERNAME
$PASSWORD
$filecheck = $UserFile, $File, $KeyFile
$result = ($filecheck | Test-Path) -notcontains $false


if($result){
    echo "Found Username and Password Files"

    $USER_NAME = $USERNAME
    $ADMIN_PASS = $PASSWORD

    $LOCALUSER = "$HOSTNAME\$USER_NAME"
    $ADMIN_PASSWORD = ConvertTo-SecureString -String $ADMIN_PASS -AsPlainText -Force


    if ($USER_NAME) {
        $LOCAL_PASSWORD = ConvertTo-SecureString -String $USER_PASS -AsPlainText -Force

        Write-Host "Username: $($LOCALUSER)" -F Green
        if($USER_NAME -eq "Administrator"){
            if ($ADMIN_PASS) {
                Write-Host "Setting Admin Password" -F Blue
                Set-LocalUser -Name Administrator -Password $ADMIN_PASSWORD -Confirm:$false
            }else{
                Write-Host "No Admin Password specified" -F Yellow
            }
        }else{
            Write-Host "Switching Admin to User: $($USER_NAME)" -F Blue
            New-LocalUser -Name "$USER_NAME" -Password $LOCAL_PASSWORD -FullName "$USER_NAME" -Description "New Admin user Generated By proxmox-cloud-init"
            Add-LocalGroupMember -Group Administrators -Member $USER_NAME
            Disable-LocalUser -Name "Administrator"
            Write-Host ""
            Write-Host "IMPORTANT!  Administrator disabled new LocalAdmin=$($USER_NAME)"
        }
    }
}